### ISSUE TITLE
Inconsistent test results on GitHub Actions

### ISSUE THREAD

**Issue by ksclarke** [ksclarke/jiiify-presentation#102]
Sometimes this test passes and sometimes it fails on GitHub Actions. I've not seen it fail locally yet. Fix this...

```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.163 s <<< FAILURE! - in info.freelibrary.iiif.presentation.v3.examples.SpecSnippetsTest
Error:  info.freelibrary.iiif.presentation.v3.examples.SpecSnippetsTest.testSpecExample  Time elapsed: 0.162 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<...love this manifest!"[]
      },
      "tar...> but was:<...love this manifest!"[,
        "id" : "de2265b5-b4b5-49c5-ab10-5f51f78389fd"]
      },
      "tar...>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at info.freelibrary.iiif.presentation.v3.examples.SpecSnippetsTest.compare(SpecSnippetsTest.java:57)
```

**Comment by ksclarke** [comment]
Fixed TextualBody so the default constructor (the one Jackson uses) doesn't supply an ID. One must pass a SkolemIriFactory to TextualBody for it to use that, similar to how we use our NOID minter.
